version: 2

jobs:

  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/Backend-Starter-Kit

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Combat Preparation
          command: docker-compose up -d

      - run:
          name: Compile Code
          command: docker-compose exec api yarn build

      - run:
          name: Code Quality
          command: docker-compose exec api yarn lint

      - run:
          name: Code Specification
          command: |
            docker-compose exec api yarn unit
            docker-compose exec api yarn _codecov --token=$CODECOV_TOKEN

      - run:
          name: E2E Specification
          command: |
            docker-compose exec api yarn start &
            docker-compose exec api yarn e2e

      - run:
          name: Deploy Application
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              docker login -u="Shyam Chen" -p="${HEROKU_TOKEN}" registry.heroku.com
              docker build -f ./tools/dev.Dockerfile -t registry.heroku.com/web-go-demo/web .
              docker push registry.heroku.com/web-go-demo/web
            elif [ "${CIRCLE_BRANCH}" == *"release"* ]; then
              docker login -u="Shyam Chen" -p="${HEROKU_TOKEN}" registry.heroku.com
              docker build -f ./tools/stage.Dockerfile -t registry.heroku.com/web-go-demo/web .
              docker push registry.heroku.com/web-go-demo/web
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u="Shyam Chen" -p="${HEROKU_TOKEN}" registry.heroku.com
              docker build -f ./tools/prod.Dockerfile -t registry.heroku.com/web-go-demo/web .
              docker push registry.heroku.com/web-go-demo/web
            fi

workflows:
  version: 2
  workflow:
    jobs:
      - build
