version: 2

jobs:

  build-test-deploy:
    docker:
      - image: cimg/base:stable

    working_directory: ~/Express-Starter

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Combat Preparation
          command: |
            docker-compose up -d app
            docker-compose exec -d app yarn serve

      - run:
          name: Compile Code
          command: docker-compose exec app yarn build

      - run:
          name: Code Quality
          command: docker-compose exec app yarn lint

      - run:
          name: Code Specification
          command: |
            docker-compose exec app yarn unit
            docker-compose exec app yarn _codecov -t $CODECOV_TOKEN

      - run:
          name: E2E Specification
          command: |
            docker-compose exec app sh -c "sleep 10"
            # docker-compose exec app yarn e2e

      - run:
          name: Docker Login
          command: |
            echo "${HEROKU_TOKEN}" | docker login -u "${HEROKU_USERNAME}" --password-stdin registry.heroku.com

      - run:
          name: Docker Build
          command: |
            docker-compose exec app sh -c "chmod +x ./tools/produce.sh"
            docker-compose exec app sh -c "./tools/produce.sh"

      - run:
          name: Heroku App
          command: |
            docker tag $APP_NAME registry.heroku.com/$APP_NAME/web
            docker push registry.heroku.com/$APP_NAME/web
            docker-compose exec -e HEROKU_API_KEY=$HEROKU_TOKEN app yarn _heroku container:release web -a $APP_NAME

workflows:
  version: 2
  workflow:
    jobs:
      - build-test-deploy
