version: 2

jobs:

  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/Backend-Starter-Kit

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Combat Preparation
          command: |
            docker-compose up -d api
            docker-compose exec -d api yarn start

      - run:
          name: Compile Code
          command: docker-compose exec api yarn build

      - run:
          name: Code Quality
          command: docker-compose exec api yarn lint

      - run:
          name: Code Specification
          command: |
            docker-compose exec api yarn unit
            docker-compose exec api yarn _codecov --token=$CODECOV_TOKEN

      - run:
          name: E2E Specification
          command: |
            docker-compose exec api sh -c "sleep 10"
            docker-compose exec api yarn e2e

      - run:
          name: Deploy Application
          command: |
            echo "CIRCLE_BRANCH is ${CIRCLE_BRANCH}"

            case "${CIRCLE_BRANCH}" in
              "develop"|*"release"*|"master")

                case "$CIRCLE_BRANCH" in
                  "develop")
                    DEPLOYMENT_ENVIRONMENT=dev
                    ;;
                  *"release"*)
                    DEPLOYMENT_ENVIRONMENT=stage
                    ;;
                  "master")
                    DEPLOYMENT_ENVIRONMENT=prod
                    ;;
                esac

                echo "DEPLOYMENT_ENVIRONMENT is ${DEPLOYMENT_ENVIRONMENT}"

                docker login -u="Shyam Chen" -p="${HEROKU_TOKEN}" registry.heroku.com
                docker build -f ./tools/$DEPLOYMENT_ENVIRONMENT.Dockerfile -t registry.heroku.com/backend-starter-kit/web .
                docker tag registry.heroku.com/backend-starter-kit/web registry.heroku.com/backend-starter-kit/web
                docker push registry.heroku.com/backend-starter-kit/web
                ;;
            esac

workflows:
  version: 2
  workflow:
    jobs:
      - build
