version: '3'

services:
  app:
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    tty: true

  dev:
    image: dev
    build:
      context: .
      dockerfile: develop.Dockerfile
    ports:
      - '3000:3000'
    tty: true

  prod:
    image: prod
    build:
      context: .
      dockerfile: produce.Dockerfile

  mongodb:
    image: mongo:4
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
